//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungryWeb.Servicios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiConfig() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HungryWeb.Servicios.ApiConfig", typeof(ApiConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/CrearAlimentoConfirm.
        /// </summary>
        internal static string CrearAlimentoConfirm {
            get {
                return ResourceManager.GetString("CrearAlimentoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/CrearAlimento.
        /// </summary>
        internal static string CreateAlimento {
            get {
                return ResourceManager.GetString("CreateAlimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/DeleteAlimentos/{0}.
        /// </summary>
        internal static string DeleteAlimento {
            get {
                return ResourceManager.GetString("DeleteAlimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/{0}.
        /// </summary>
        internal static string GetAlimento {
            get {
                return ResourceManager.GetString("GetAlimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/.
        /// </summary>
        internal static string GetAllFood {
            get {
                return ResourceManager.GetString("GetAllFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Ordenes/{0}.
        /// </summary>
        internal static string GetDetailedOrder {
            get {
                return ResourceManager.GetString("GetDetailedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Ordenes/.
        /// </summary>
        internal static string GetSlimOrders {
            get {
                return ResourceManager.GetString("GetSlimOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://192.168.15.5:5000/api/Alimentos/UpdateAlimentos.
        /// </summary>
        internal static string UpdateFood {
            get {
                return ResourceManager.GetString("UpdateFood", resourceCulture);
            }
        }
    }
}
